### ISSUE TITLE
Add info about new release procedures

### ISSUE THREAD

**Issue by davetcoleman** [davetcoleman/moveit_merge#3]
@130s could you extend the section on release procedures after the merge please? it might be obvious and trivial, I just want to note your plan

**Comment by davetcoleman** [comment]
Also what are your thoughts on changing the metapackage `moveit-full` to `moveit` so it matches the new repo like the old stacks did?

**Comment by 130s** [comment]
See #4 for your request.

> Also what are your thoughts on changing the metapackage `moveit-full` to `moveit` so it matches the new repo like the old stacks did?

+1

Note that the [current `moveit-full` contains 5 packages](https://github.com/ros-planning/moveit_metapackages/blob/b89e9ae0d6d0fe5cf8172ee59387464642b46f99/moveit_full/package.xml#L17), whereas the new `moveit` metapkg will hold more than that. I guess users can easily choose which packages they need and don' always install by metapackage, so having one big meta package does only good without harm.

**Comment by davetcoleman** [comment]
I just added a section about how I think the metapackage should be handled - let me know what you think https://github.com/davetcoleman/moveit_merge/commit/7f9a491b1c1c016f037fcbc8a81c7a444710414f

**Comment by 130s** [comment]
http://discourse.ros.org/t/migration-to-one-github-repo-for-moveit/266/23

> >   Do you guys plan to do a catch up release of all the moveit packages in the new repository that day so that they have the same version number? Or will you wait until one of them needs to be released and release them all then?
> 
> I assume we will wait until one of them needs to be released and then release all of them. @130s is the lead for MoveIt! releases, however, and I'm hoping he'll add a section to the migration notes about his plan

+1 for wait.

It may or may not be worthwhile on WMD to have binaries from the new merged repository (even from shadow-fixed repo) so that we can have people test. I'm not sure...since people on WMD will most likely work on source with their own forks and will make (hopefully a bunch of) pull requests. So binaries are probably not required for WMD.
