### ISSUE TITLE
Versions in the new moveit metapkg and its member packages

### ISSUE THREAD

**Issue by 130s** [davetcoleman/moveit_merge#9]
Continuing from https://github.com/davetcoleman/moveit_merge/issues/3#issuecomment-236694427

@davetcoleman @v4hn @mikeferguson @IanTheEngineer
I'd want agreement for the version for the new `moveit` meta package and its member packages, in order to make releases per each distro. I propose Option-A and B so give opinion for either options, or another option is welcomed. 

Since Jade release needs to happen soon https://github.com/ros-planning/moveit/issues/22 I appreciate your quick input (sorry, this proposal should've been made way earlier..).

To release packages under a meta-package umbrella, they all need to be the same version AFAIK. Currently there's a version deviation per packages (full set can be seen [here](http://repositories.ros.org/status_page/compare_indigo_jade.html?q=moveit_)) as the table below.

| **Current (meta)pkgs** | Indigo | Jade | Kinetic |
| --- | --- | --- | --- |
| moveit_commander | 0.6.1 | 0.6.1 |  |
| moveit_core | 0.7.2 | 0.8.2 |  |
| moveit_ikfast | 3.1.1 | 3.2.0 |  |
| moveit_planners | 0.7.0 | 0.6.7-0 |  |
| moveit_plugins | 0.5.7 | 0.5.6 |  |
| moveit_ros | 0.7.2 | 0.6.6 |  |
| moveit_setup_assistant | 0.7.2 | 0.7.1 |  |
| **Standalone packages** |  |  |  |
| moveit_msgs | 0.7.2 | 0.8.1 |  |
| srdfdom | 0.3.1 | 0.3.1 |  |
| warehouse_ros | 0.8.8 | 0.9.0 |  |

My proposal for the new `moveit` package:

| **Proposed version for new moveit pkg** | Indigo | Jade | Kinetic |
| --- | --- | --- | --- |
| Option-A | 0.7 | 0.8 | 0.9 |
| Option-B | 0.9 | 0.10 | 0.11 |
- Option-A: Stick to the current version as much as possible. Mainly driven by the versions of _core, _ros, _msgs. Good thing is we won't need to make a new release of `moveit_msgs` just for updating their versions.
- Option-B: Increment all distro to the numbers that are not structurally used in MoveIt!. I guess we better update `moveit_msgs`'s version too.

I prefer Option-B but I don't find any strong reason not to keep the versions so Option-A is possible.

Caviat of my proposal above:
- Version of `moveit_ikfast` needs to be downgraded (unless we decide to use the numbers  larger than 3.X)

**Comment by jspricke** [comment]
Hi, @v4hn asked me to comment regarding the downgrade of ikfast. `ros-indigo-moveit-ikfast` in trusty has the version: 3.1.1-0trusty-20160629-033025-0700. As this is generated by bloom, the new version would have a version of 0.7-0trusty... This would mean apt would not select it for an upgrade (until it get's bigger then 3.1.1 again ;) ).

One solution would be to add an [epoch](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version) to the package, but I haven't seen an option in bloom to do this. (@wjwwood can you comment?).

The other option is obviously to go with 3.x ;).

**Comment by davetcoleman** [comment]
_Note_: Rational on moveit_ikfast - version 1 was for arm_navigation, version 2 was some messy version that supported arm_nav and moveit, and version 3 was the rewrite that I did that renamed it and turned it into moveit_ikfast as we know it today.

I was worried about its version number and one thought was to deprecate that package and move it into `moveit/moveit_ros/planning` where the KDL, IMA, and SRV kinematic solvers live, putting it into the folder `ikfast_kinematics_plugin`. 

If there are difficulties downgrading the version of ikfast, I think we should post-pone releasing a new version of the ikfast plugin into bloom (by adding a CATKIN_IGNORE to it?) because:
- There are actually no updates to ikfast since its last release in indigo and jade
- No package should/needs to depend on ikfast. It is simply a tool to generate other packages custom to other robots
- MoveIt! jade is blocking the ROS buildfarm sync

**Comment by davetcoleman** [comment]
To answer @130s proposal, I like **Option A** sticking to the closest version possible. I assume you mean, however, that it would be version `0.7.3`, `0.8.3`, and `0.9.3` so that all packages (except ikfast) are upgraded by a minor tick? Otherwise `moveit_core` would be downgraded.

**Comment by wjwwood** [comment]
You can modify the Debian files how ever you like by patching them in bloom. So adding an epoch to the version would be possible. 

As you describe it, the package seems to be infrequently updated and so, could just leave it as a separate repository?

You definitely should not consider downgrading the version number of it, or any package for that matter. That's a really bad solution in my opinion. You could also eol the package and make a new package to replace it or merge it with another replayed package.

**Comment by 130s** [comment]
Thanks for the opinions. I guess we're making a consensus so far as follows. If there's no objections (maybe for half a day? Too hasty?), I'll go ahead opening PRs to implement these.
- Move `moveit_ikfast` into [moveit/moveit_ros/planning](https://github.com/ros-planning/moveit/tree/kinetic-devel/moveit_ros/planning) and add `CATKIN_IGNORE`, won't be released for now.
- Proposed version for new moveit pkg:
  
  | **Proposed version for new moveit pkg** | Indigo | Jade | Kinetic |
  | --- | --- | --- | --- |
  | Option-A | 0.7.3 | 0.8.3 | 0.9.3 (*1) |

*1. There's no 0.9.x so far in MoveIt! world but I guess [what Dave suggests](https://github.com/davetcoleman/moveit_merge/issues/9#issuecomment-239515291) makes sense since other 2 distros are aligned at 0.x.3.

**Comment by davetcoleman** [comment]
> Move moveit_ikfast into moveit/moveit_ros/planning and add CATKIN_IGNORE, won't be released for now.

Lets certainly give the ikfast topic more input from others, in an different issue on the main repo.

+1 to moving forward with releasing everything else with those version numbers.

**Comment by 130s** [comment]
[Proposed versions](https://github.com/davetcoleman/moveit_merge/issues/9#issuecomment-239541170) are [accepted](https://github.com/ros-planning/moveit/pull/41#issuecomment-239645858). 

Now, release.

**Comment by 130s** [comment]
> Now, release.

Oh wait, ikfast. I'll open PRs.
